### PR TITLE
Upgrade to Stencil one

### PR DESCRIPTION
**Pull request by khaledosman**
Upgrade app to stencil v1

### CODE REVIEW

**Comment by hcavalieri** [comment]
Sorry for the wait, @khaledosman ! Thank you for the contribution 🙌

I'm trying to figure out 2 things before merging the PR:

1. Shouldn't we wait until v1 gets out of alpha?
2. Why did you import "h" from `@stencil/core` in some components? What is that for?

Also, the [Netlify build worked](https://deploy-preview-2--stencil-realworld.netlify.com/), apparently, but there are some things off... did you observe this behavior in development?

Anywho, we definitely need to update dependencies! Let's just try to figure these points out :)

**Comment by khaledosman** [comment]
1. Yes waiting would probably be best unless we want to do another release after, I'll keep the PR up to date till its finally released
2. Its one of the breaking changes in stencil 1.0 see https://github.com/ionic-team/stencil/blob/core-refactor/BREAKING_CHANGES.md

Not really the dev build worked fine for me after fixing the breaking changes, last time I checked however running the unit tests didn't work due to a bug in stencil which should be fixed on release. Can you explain what exactly was off?

**Comment by hcavalieri** [comment]
1. Cool! Let's wait until v1 lands, then :)
2. Hm... I wonder why this is the case... Anywho, good work!

I'll test it somewhere in the following weeks, I believe there might be a breaking change that broke the current app, have to do further inquiring 🤔 Oh, and thanks for the quick reply, Khaled :D

**Comment by khaledosman** [comment]
v1 is officially released, I've updated the dependencies accordingly

**Pull request merged**
